# Generated by Django 4.2.5 on 2023-09-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Aluno')),
                ('dtNascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('nome_mae', models.CharField(max_length=150, verbose_name='Nome da Mãe')),
                ('nrTelCelular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('conclusao', models.CharField(max_length=15, verbose_name='Ano de conclusão')),
                ('atendimento', models.CharField(max_length=150, verbose_name='Atendente')),
                ('data_pedido', models.DateField(verbose_name='Data do pedido')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('done', models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], default='done', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
